---


- name: PLAY 1 GENEREATE INITIAL CONFIG FILES FOR R1 USING ROLES MODULE
  hosts: localhost
  connection: local
  # gather_facts: no


  roles:
    - r1
    # - name: TASK 1 GENERATE INITIAL CONFIG FILES FOR R1
    #    template:
    #       src: "./templates/r1_temp.j2" 
    #       dest: "./renderedConfigs/routers/r1.cfg"

    # - name: TASK 1 GENERATE INITIAL CONFIG FILES FOR R2
    #    template:
    #       src: "./templates/r1_temp.j2"
    #       dest: "./renderedConfigs/routers/r2.cfg"